const jwt = require('jsonwebtoken');
const JWT_KEY = process.env.JWT_KEY;


const validateToken = (req, res, next) => {
    const headers = req.headers || {};
    const token = headers.authorization;
    
    if (!token) {
        res.status(401).send({message: "Invalid Token"})
    }
    let decodedToken;
    try {
        // 1. Validate if the token is Generated By me
        // Compare the signature
        // 2. Checks whether the token is expired or not
        decodedToken = jwt.verify(token, JWT_KEY);
                        
    } catch (e) {
        console.log("JWT Error", e);
        return res.status(401).send({message: "Invalid User"});
    }
    
    console.log("Valid User", decodedToken);
    next();
}


module.exports = {validateToken};